version: '3.8'
services:
  db:
    image:  postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
volumes:
  db:
    driver: local
